apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "currencyservice.fullname" . }}
  labels:
    {{- include "currencyservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "currencyservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "currencyservice.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: currencyservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: DISABLE_PROFILER
              value: {{ .Values.env.DISABLE_PROFILER | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
