replicaCount: 1

image:
  repository: registry.gitlab.unige.ch/the_final_project/docker-project/cartservice
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

service:
  type: ClusterIP
  port: 8080

env:
  REDIS_ADDR: "redis:6379"
  LISTEN_ADDR: "0.0.0.0:8080"

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
